branch-defaults:
  demo:
    environment: StellarFinder-env
environment-defaults:
  StellarFinder-env:
    branch: null
    repository: null
global:
  application_name: StellarFinder
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
